"""Architecture layers, mirrored from ``vendor/upstream/layers/``.

Every module here states which canonical file it mirrors and, where it differs,
why. See ``PARITY.md`` (generated by ``tests/test_arch_parity.py``) for the
numeric evidence.
"""
from .bitlinear import BitLinear, activation_quant, make_linear, weight_quant
from .norm import QKRMSNorm, RMSNorm
from .attention import GQA, RotaryEmbedding, apply_rope_optimized, rotate_half
from .ffn import MertFormerFFN
from .liquid import LiquidCell, LiquidMixer, liquid_loop_quantized, quant_for_liquid
from .moe import MoE, BitSwiGLU, LiquidRouter, moe_capacity
from .qinn import UnitaryQINN, newton_schulz_inverse
from .block import MertFormerBlock

__all__ = [
    "BitLinear",
    "activation_quant",
    "weight_quant",
    "make_linear",
    "RMSNorm",
    "QKRMSNorm",
    "GQA",
    "RotaryEmbedding",
    "rotate_half",
    "apply_rope_optimized",
    "MertFormerFFN",
    "LiquidCell",
    "LiquidMixer",
    "quant_for_liquid",
    "liquid_loop_quantized",
    "MoE",
    "BitSwiGLU",
    "LiquidRouter",
    "moe_capacity",
    "UnitaryQINN",
    "newton_schulz_inverse",
    "MertFormerBlock",
]
