"""Generate repro/cuda.lock from the current system.

This script is safe to run on CPU-only systems; it will emit placeholders.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
import subprocess
import sys

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = PROJECT_ROOT / "repro" / "cuda.lock"


def _run(cmd: list[str]) -> str | None:
    try:
        return subprocess.check_output(cmd, encoding="utf-8").strip()
    except Exception:
        return None


def _first_line(value: str | None) -> str | None:
    if not value:
        return None
    return value.splitlines()[0].strip()


def main() -> None:
    driver = _first_line(_run(["nvidia-smi", "--query-gpu=driver_version", "--format=csv,noheader"]))
    cuda_smi = _first_line(_run(["nvidia-smi", "--query-gpu=cuda_version", "--format=csv,noheader"]))
    gpu_name = _first_line(_run(["nvidia-smi", "--query-gpu=name", "--format=csv,noheader"]))

    torch_cuda = None
    torch_cudnn = None
    torch_nccl = None
    torch_version = None

    try:
        import torch  # type: ignore

        torch_version = getattr(torch, "__version__", None)
        torch_cuda = torch.version.cuda
        try:
            torch_cudnn = torch.backends.cudnn.version()
        except Exception:
            torch_cudnn = None
        try:
            torch_nccl = torch.cuda.nccl.version() if torch.cuda.is_available() else None
        except Exception:
            torch_nccl = None
        if torch.cuda.is_available() and gpu_name is None:
            try:
                gpu_name = torch.cuda.get_device_name(0)
            except Exception:
                gpu_name = None
    except Exception:
        pass

    lines = [
        "# Auto-generated by scripts/write_cuda_lock.py",
        f"timestamp_utc={datetime.now(timezone.utc).isoformat()}",
        f"driver={driver or 'unknown'}",
        f"cuda={torch_cuda or cuda_smi or 'unknown'}",
        f"cudnn={torch_cudnn or 'unknown'}",
        f"nccl={torch_nccl or 'unknown'}",
        f"torch={torch_version or 'unknown'}",
        f"gpu={gpu_name or 'unknown'}",
    ]

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    sys.exit(main())
